# Generated by Django 5.2.3 on 2025-06-27 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AddField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
