# Generated by Django 5.2.3 on 2025-06-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_meal_id_remove_rating_id_meal_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='uuid',
        ),
        migrations.AddField(
            model_name='meal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
